project_name: qiniuCertAutoRenewer
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod download
builds:
  - main: ./cmd/qiniuCertAutoRenewer
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
    goarm:
      - '7'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
        goarm: '7'
    ldflags:


archives:
- format: binary

snapshot:
  version_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Merge pull request'
